backend/account/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'account'
urlpatterns = [
    path('login/',views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('register/', views.registerpage, name='registerpage'),
    path('', views.home, name='home'),
    path('createcompany/', views.createcompany, name='createcompany'),
    path('createstaffaccount/', views.createstaffaccount, name='createstaffaccount'),
    path('user_update_view/<int:id>/', views.user_update_view, name='user_update_view'),


    path('reguseraccount/', views.reguseraccount, name='reguseraccount'),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/templates/companyprofile.html
{% extends 'base.html' %}

{% block content %}
<div class="col-4">
    <form action="{% url 'account:createcompany' %}" method="POST">
        {% csrf_token %}
        <!-- {{form.as_p}} -->
        {% for field in form %}
         {{field.label}}{{field}}
        {% endfor %}
        <input type="submit" value="Create Company Profile" class="btn btn-success mt-2">
    </form>
</div>
    {% endblock content %}

backend/templates/createstaffaccount.html
{% extends 'base.html' %}

{% block content %}


<div class="row justify-content-center">
  <div class="col-md-6">
    
    <!-- Bordered table -->
    <div class="">
      <div class="card shadow">
        <div class="card-body">
          <h5 class="card-title">Create User Account</h5>
          
          <form action="{% url 'account:reguseraccount' %}" method="post">{% csrf_token %}
          <div class="form-group">
            
            {{ form }}
            
            <button class="btn btn-lg btn-primary btn-block" type="submit">Create Account</button>

          </form>
          
        </div>
      </div>
    </div> <!-- Bordered table -->
  </div>

</div>

{% endblock content %}

backend/templates/home.html
{% extends 'base.html' %}

{% block content %}



{% endblock content %}

backend/templates/line_setup.html
{% extends 'base.html' %}

{% block content %}



{% endblock content %}

backend/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Login</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="#" class="logo d-flex align-items-center w-auto">
                  <img src="{% static 'assets/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">Garment</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your username & password to login</p>
                  </div>

                  <form class="row g-3 needs-validation" novalidateaction="" method="post">{% csrf_token %}

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="text" name="username" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please enter your username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="#">Star Business IT Solution</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

backend/templates/register.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'account:registerpage' %}" method="POST">
    {% csrf_token %}
    
              <!-- {{ form }} -->
    {% for field in form %}
     {{field.label}}{{field}}
    {% endfor %}
    <input type="submit" value="Create User">
</form>

{% endblock content %}

backend/templates/user_update_view.html
{% extends 'base.html' %}

{% block content %}

<div class="card mx-5 col-6">
    
<div class="card-body">
<form method="POST">
    <h4>Update User Role</h4><hr>
    <!-- Security token by Django -->
    {% csrf_token %}

    <!-- form as paragraph -->
    {{ form.as_p }}

    <input type="submit" value="Update" class="btn btn-sm btn-primary">
</form>
</div>
</div>

{% endblock content %}